apiVersion: batch/v1
kind: Job
metadata:
  name: before-install
spec:
  ttlSecondsAfterFinished: 2
  template:
    spec:
      containers:
      - name: clear
        image: "alpine:3.15.4"
        command:
        - /bin/ash
        - -c
        - |
          rm -R /mnt/data/*
          rm -R /mnt/mysql/*
          rm -R /mnt/data_backup/*
          rm -R /mnt/mysql_backup/*
        volumeMounts:
            - name: per1-storage
              mountPath: "/mnt/data"
            - name: perdb1-storage
              mountPath: "/mnt/mysql"
            - name: per2-storage
              mountPath: "/mnt/data_backup"
            - name: perdb2-storage
              mountPath: "/mnt/mysql_backup"
      volumes:
      - name: per1-storage
        persistentVolumeClaim:
          claimName: phpweb1-pv-claim
      - name: perdb1-storage
        persistentVolumeClaim:
          claimName: phpweb2-pv-claim
      - name: per2-storage
        persistentVolumeClaim:
          claimName: phpweb1c-pv-claim
      - name: perdb2-storage
        persistentVolumeClaim:
          claimName: phpweb2c-pv-claim
      restartPolicy: Never
  backoffLimit: 0
