name: doc_dev
on:
  push:
    branches:
      - test
env:
  TAG: tl19b1
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: auth
        uses: docker/login-action@v1
        with:
          username: bb8312
          password: ${{ secrets.DPASS }}
      - name: build-push-action
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bb8312/phpdev:${{ env.TAG }}
  kubeval:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: manifest
      uses: instrumenta/kubeval-action@master
      with:
       files: ./manifests
  slack:
    name: notify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: notify
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: notification-plan
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Kubernetes manifests have been passed through the Kubeval checks. See bb8312/phpdev:${{ env.TAG }} docker image.'
        SLACK_TITLE: 'Push happened on test!'
        SLACK_USERNAME: SuperHook
        SLACK_WEBHOOK: ${{ secrets.URL }}
